name: Lighthouse CI
on:
  pull_request:
  push:
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Run Lighthouse
        run: npx @lhci/cli autorun
