receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging: {}
  prometheus: {}
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
